language: node_js
node_js:
  - "7"

dist: trusty

addons:
  sonarqube:
    organization: "usi"
    token:
      secure: "c209fa9b995ec14ab100e9f0b95a962e158da1c5"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false